[GDrive]
type = drive
client_id = 800569506797-9128u1vn2d8ftdf133u47t9for46ei8b.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AQvPyIPwwmEjV81Pyd_OBab8n1UysJNdAJh0Nk-FyxM50lg7vkn3Z9IZ7P1KvvrM_C3v896Kuwg-lAxeVY44jjtPoKiDMAHNTKg1jCT6-9GPda1qDSO6vpORTqXkY--2heCnKNObpnkjQrAZkEV10UmzyWqQ4O6IX6PbY1prIpDBkFmvRDiIZvx1l2RvYeybodyMcYUqaCgYKAf8SARISFQHGX2Mij6cfR9ZiflXS0cGPbhMGAg0207","token_type":"Bearer","refresh_token":"1//0eEDbo4sFynLXCgYIARAAGA4SNwF-L9Ir13laF7qSH9tSG8xVM6AwAGX5FbOquPBiQU9G0hNRt71wkwg5e2F3paAYmI5DznEFKBo","expiry":"2026-04-29T01:22:38.800689933Z","expires_in":3599}
team_drive = 

