add_newline = true

scan_timeout = 1000
command_timeout = 60000

[character]
success_symbol = '[->](bold green)'
error_symbol = '[->](bold red)'

[cmd_duration]
min_time = 0
show_milliseconds = false
format = '[\($duration\)]($style) '
style = 'bold blue'

[directory]
truncation_length = 0
truncate_to_repo = false
